### ISSUE TITLE
关于论文中表3处理时间的问题？

### ISSUE THREAD

**Issue by tuqiangwang** [yi94code/HRSOD#4]
谢谢你们做的贡献，我很喜欢你们的论文！这里关于处理时间或者说是帧率，我有几个问题，烦请赐教！
1、阅读论文后，表3中的Ours*和Ours表示1024*1024和384*384的处理时间，请问分别是0.39秒一张和0.05秒一张，是吗？
换算为帧率即为2.564和20，请问我这样的理解对吗？

2、关于更大分辨率的图片，你们有进行测试吗，若有，他们的帧率是多少？

谢谢您的回答！！！

**Comment by yi94code** [comment]
1、是的。
2、没有。
